### ISSUE TITLE
Use zlib to compress and decompress image data

### ISSUE THREAD

**Issue by modi12jin** [atomic14/esp32-tv#11]
@cgreening Sorry to bother, is it feasible to send to esp32 for decompression with zlib compression on the server side

**Comment by modi12jin** [comment]
https://components.espressif.com/components/espressif/zlib

**Comment by cgreening** [comment]
On the image data side there's not a huge amount of benefit as the JPEG images are already heavily compressed. There would be some marginal benefit on the audio side of things, potentially that is quite compressible, but again, compared to the image sizes it's a small amount of data.

**Comment by modi12jin** [comment]
Thanks for your reply！

**Comment by modi12jin** [comment]
Someone wrote an example for the component
https://github.com/nopnop2002/esp-idf-zlib
