### ISSUE TITLE
Some SD-cards are not recognized 

### ISSUE THREAD

**Issue by joekam54** [atomic14/esp32-tv#19]
Hello, I found out that some SD-cards could not get mounted-are not recognized.

Device Cheap-Yellow-Display.

I have 2 manufact. Sandisk 16 GB , Intenso 4 GB, the Sanisk card works with the player, the Intenso not.

Attached the serial outputs  for both. 
both are class10 card's, 
The Intenso works with the device with another code flawless.

![image](https://github.com/atomic14/esp32-tv/assets/160762514/19aeb3e7-11d8-43e3-96a4-1501aabd8d98)
[serial-intenso.txt](https://github.com/atomic14/esp32-tv/files/14917266/serial-intenso.txt)
[serial-sandisk.txt](https://github.com/atomic14/esp32-tv/files/14917267/serial-sandisk.txt)

**Comment by cgreening** [comment]
I can only suggest is to decrease the clock rate that is used to talk to the SDCard.

Line 72 of SDCard.cpp

```
  m_host.max_freq_khz = SDMMC_FREQ_52M;
```

Try changing this to `SDMMC_FREQ_26M` or even a hard coded very low value like 10000000.

Also, make sure you are power cycling the board completely.

There may be more information when the board first powers up, but currently it will go into a boot loop when the SD Card fails.

**Comment by cgreening** [comment]
Can you give it a go with the latest firmware - I want to see if there are more logs on startup and this change should prevent the boot loop.

**Comment by joekam54** [comment]
[cyd-log_new_PF-ini.txt](https://github.com/atomic14/esp32-tv/files/14946961/cyd-log_new_PF-ini.txt)
Hi ,  updated the Platformioini with your changes, --There are more logs nw, but behavior is the same. Log attached

**Comment by KevynWithaY** [comment]
I've had success by using 1-bit mode in the sdmmc section of the SDCard class, using the miso, mosi and clk lines only. Card mounts and I can even use higher speed. Just gotta disconnect GPIO2 when you need to flash.

**Comment by joekam54** [comment]
> I can only suggest is to decrease the clock rate that is used to talk to the SDCard.
> 
> Line 72 of SDCard.cpp
> 
> ```
>   m_host.max_freq_khz = SDMMC_FREQ_52M;
> ```
> 
> Try changing this to `SDMMC_FREQ_26M` or even a hard coded very low value like 10000000.
> 
> Also, make sure you are power cycling the board completely.
> 
> There may be more information when the board first powers up, but currently it will go into a boot loop when the SD Card fails.

Hi, I patched my cde with your last changes and tryed with 26M and it also was not working, but it works with the default 
  m_host.max_freq_khz = SDMMC_FREQ_DEFAULT;
  
... so this in 20 mhz
Funny thing I have tested it with a few different sdcard brand' before the cange it only worked wih the Sandisk Ultra from the Picture.

**Comment by davidhampgonsalves** [comment]
I had the same experience with two of my SD cards (and switching to `SDMMC_FREQ_DEFAULT` resolved it). 

@cgreening Would you be interested in a small PR to change to using SDMMC_FREQ_DEFAULT or do you think it would negatively impact other use cases?

**Comment by cgreening** [comment]
Let's lower it down. I think there's a lot of cards that can't handle the full speed.

Pull request would be much appreciated! Thank you!

**Comment by davidhampgonsalves** [comment]
Thanks @cgreening for the amazing project. https://github.com/atomic14/esp32-tv/pull/23 is ready for review.
