### ISSUE TITLE
Only one Video is played from the SD-Card

### ISSUE THREAD

**Issue by joekam54** [atomic14/esp32-tv#20]
Hello,

Device: Cheap-Yellow-Display

First of all thank you for the last changes,  The player is now t stopping anymore playback when the Video is ended, instead it is looping now and plays it:-) thats great news.
Butit is only Playing one Video stored on the SD Card insteand off all what i would expect;-) not sure how the design spec for it is But from my point of view it would be great if all videos are played in a loop and the same sequence order.  (eg. name a-z, or 1-x).

Thank you for the great Job done so far!

**Comment by cgreening** [comment]
This would be quite hard to do with the current architecture.

The code is designed to work with an infra red control with the user switching between channels. Playing the first video on the card is really just a "demo mode".

A work around would be to concatenate all the videos into one longer video and play that.

**Comment by joekam54** [comment]
..understand, yes the workaround is what I thought about too, Iam still a beginner and will hopefully understand your code better. Basically Iam thining about a flow like after initializing the SD-Card reading the filemames, and sae a playlist. Backing also the duration of the Video into the filename (struckture) will give a kind of playlist and than change your remote control code in such a way that it switches on the next spot based on this list , but there will be a long way for me to come that far ;-) .

**Comment by KevynWithaY** [comment]
You could just auto switch to the next channel after the current channel is finished
